---
- hosts: all
  vars:
    user_email: anthony.lai@hostname.io
    user_name: Anthony Lai
  tasks:
    - name: Copy global gitconfig
      template: src=templates/git/gitconfig dest=~/.gitconfig
    - name: Copy global gitignore
      template: src=templates/git/gitignore dest=~/.gitignore
