---
- hosts: all
  roles:
  - role: osxc.packages
    brew_packages:
    - ruby
  tasks:
    - name: ensure librarian-chef is installed
      gem: name=librarian-chef
    - name: ensure chef is installed
      gem: name=chef
    - name: ensure librarian-ansible is installed
      gem: name=librarian-ansible
    - name: ensure ansible is installed
      gem: name=ansible 
      
    - name: ensure knife-solo is installed
      gem: name=knife-solo
    
kitchen-vagrant
vagrant-hostmanager
vagrant-salt
vagrant-ansible
vagrant-aws
vagrant-digitalocean
vagrant-snap
